project:
  type: website
  output-dir: docs

website:
  title: "Rudransh Singh"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: Projects

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false
